/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OpportunisticSensingServer;

/**
 *
 * @author Claudio Gisch e Paulo Lanzarin
 */
public class MainWindow2 extends javax.swing.JFrame {
    
    private String htmlBase = "<hmtl><p><strong><span style=\"font-family:arial,helvetica,sans-serif;\"><span style=\"color: rgb(0, 128, 0);\"><span style=\"background-color: rgb(240, 255, 240);\">#</span></span></span></strong></p></html>";
    private String connectedText = "Conectado";
    private String connectionFailedText = "Conexão falhou";
    private boolean connectionCanceled = false;
    private ServerThread st = null;
    /**
     * Creates new form MainWindow2
     * @param st the server Thread
     */
    public MainWindow2(ServerThread st) {
        initComponents();
        this.st = st;
        this.st.setWindow(this);
    }
    
    public boolean startServerThread() 
    {
        if(this.st.getWindow() != null)
        {
            this.st.start();
            return true;
        }
        
        return false;
    }
    
    public void appendTextInfoArea(String s)
    {
        this.informationArea.setText(this.informationArea.getText()+s+"\n");
    }
    
    public boolean isConnectionCanceled()
    {
        return this.connectionCanceled;
    }
    
    public void setStatusText(String s)
    {
        this.statusText.setText(s);
    }
    
    public void setButtonText(String s)
    {
        this.cancelConnectionBtn.setText(s);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusText = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        cancelConnectionBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        informationArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        statusLabel.setText("Status:");

        cancelConnectionBtn.setText("Cancelar Conexão");
        cancelConnectionBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelConnectionBtnMouseClicked(evt);
            }
        });
        cancelConnectionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelConnectionBtnActionPerformed(evt);
            }
        });

        informationArea.setColumns(20);
        informationArea.setRows(5);
        jScrollPane1.setViewportView(informationArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cancelConnectionBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(statusLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(statusText, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 40, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusText, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelConnectionBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelConnectionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelConnectionBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelConnectionBtnActionPerformed

    private void cancelConnectionBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelConnectionBtnMouseClicked
        this.connectionCanceled = true;
    }//GEN-LAST:event_cancelConnectionBtnMouseClicked

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelConnectionBtn;
    private javax.swing.JTextArea informationArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel statusText;
    // End of variables declaration//GEN-END:variables
}
